allowBuilds:
  '@ffprobe-installer/darwin-arm64': set this to true or false
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  ffmpeg-static: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
